name: Build go-echo image
on:
  push:
    branches:
      - master

env:
  SERVICE: go-echo
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env
        run: |
          REF_SHORT="${GITHUB_REF##*/}"
          SHA_SHORT="${GITHUB_SHA:0:8}"
          IMAGE_NAME="${REGISTRY_URL}/${GITHUB_REPOSITORY_OWNER}/tools/${SERVICE}"
          [[ "${REF_SHORT}" == "master" ]] && IMAGE_TAG=latest

          echo "REF_SHORT=${REF_SHORT}"               >> "${GITHUB_ENV}"
          echo "SHA_SHORT=${SHA_SHORT}"               >> "${GITHUB_ENV}"
          echo "IMAGE_NAME=${IMAGE_NAME}"             >> "${GITHUB_ENV}"
          echo "IMAGE_TAG=${IMAGE_TAG}"               >> "${GITHUB_ENV}"

      - name: Build docker image
        run: |
          docker build . \
            -f ./Dockerfile \
            -t "${IMAGE_NAME}:${IMAGE_TAG}" \
            --build-arg image_source="https://github.com/${GITHUB_REPOSITORY}" \

      - name: Log into registry
        run: echo "${REGISTRY_PASSWORD}" | docker login "${REGISTRY_URL}" -u "${REGISTRY_USERNAME}" --password-stdin

      - name: Push docker image
        run: |
          DIGEST=$(docker push "${IMAGE_NAME}:${IMAGE_TAG}" | awk '/digest/ {print $3}')
          echo "DIGEST=${DIGEST}" >> "${GITHUB_ENV}"
